"""Added new table in name new_columns.

Revision ID: 0b72ceba9937
Revises: 718792696921
Create Date: 2025-03-27 12:58:13.886680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b72ceba9937'
down_revision = '718792696921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('column_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name')
    )
    op.drop_table('times_test')
    op.drop_table('report_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agency_related_to', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('offer_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('property_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('offer_vertical', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('owner_new_vertical', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('owner_full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('agency_or_direct', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('agency_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('brand_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('client_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('client_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_gov', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('finance_offer_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('type_of_business', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='report_test_pkey')
    )
    op.create_table('times_test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('site', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('ros_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('site_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('package_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('site_type', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('lighting_type', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('sitetype_info', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('media_type', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('width_feet', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('width_inches', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('height_feet', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('height_inches', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('color_bleed_area', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('no_of_sites', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('announcement_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('material_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rate_card', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type_of_display', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('sub_location', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('landmark', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('width', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('height', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('area', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('towards', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('property', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('sales_manager', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('offer_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('offer_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('blocking_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('advance_booking_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('advance_book_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('advance_book_end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('advance_book_client_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('remaining_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agency', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('client_code', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('current_client', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('campaign_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('campaign_end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('verification_comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='times_test_pkey'),
    sa.UniqueConstraint('site', name='times_test_site_key')
    )
    op.drop_table('new_columns')
    # ### end Alembic commands ###
