"""altered file_name, file_path, table_name column in uploaded_file_records table

Revision ID: 125dad6e3cdb
Revises: 52fdf621cf59
Create Date: 2025-03-20 10:48:46.770932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125dad6e3cdb'
down_revision = '52fdf621cf59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file_records', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('table_name',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.create_unique_constraint(None, ['file_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('table_name',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###
