"""Added table_name column in uploaded_file_records table

Revision ID: 52fdf621cf59
Revises: 633b556fc7bb
Create Date: 2025-03-20 09:22:28.175924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52fdf621cf59'
down_revision = '633b556fc7bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('media_property_occupancy_report', schema=None) as batch_op:
    #     batch_op.drop_column('package_name')
    #     batch_op.drop_column('net_revenue')

    # with op.batch_alter_table('media_property_occupancy_status', schema=None) as batch_op:
    #     batch_op.drop_column('2nd_blocking_till')
    #     batch_op.drop_column('1st_blocked_for')
    #     batch_op.drop_column('third_blocked_till')
    #     batch_op.drop_column('1st_blocking_till')
    #     batch_op.drop_column('2nd_blocked_for')
    #     batch_op.drop_column('2nd_blocked_by')
    #     batch_op.drop_column('third_blocked_by')
    #     batch_op.drop_column('third_blocked_for')
    #     batch_op.drop_column('1st_blocked_by')

    with op.batch_alter_table('uploaded_file_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_name', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file_records', schema=None) as batch_op:
        batch_op.drop_column('table_name')

    with op.batch_alter_table('media_property_occupancy_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('1st_blocked_by', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('third_blocked_for', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('third_blocked_by', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('2nd_blocked_by', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('2nd_blocked_for', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('1st_blocking_till', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('third_blocked_till', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('1st_blocked_for', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('2nd_blocking_till', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    with op.batch_alter_table('media_property_occupancy_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_revenue', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('package_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
