"""Added po_date in report table

Revision ID: 718792696921
Revises: ac92f8b7cb88
Create Date: 2025-03-27 09:01:43.100102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718792696921'
down_revision = 'ac92f8b7cb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_property_occupancy_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('po_date', sa.Date(), nullable=True))

    # with op.batch_alter_table('media_property_occupancy_status', schema=None) as batch_op:
    #     batch_op.drop_column('third_blocked_till')
    #     batch_op.drop_column('third_blocked_for')
    #     batch_op.drop_column('1st_blocked_by')
    #     batch_op.drop_column('2nd_blocked_by')
    #     batch_op.drop_column('third_blocked_by')
    #     batch_op.drop_column('2nd_blocked_for')
    #     batch_op.drop_column('1st_blocked_for')
    #     batch_op.drop_column('1st_blocking_till')
    #     batch_op.drop_column('2nd_blocking_till')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_property_occupancy_status', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('2nd_blocking_till', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        # batch_op.add_column(sa.Column('1st_blocking_till', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        # batch_op.add_column(sa.Column('1st_blocked_for', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        # batch_op.add_column(sa.Column('2nd_blocked_for', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        # batch_op.add_column(sa.Column('third_blocked_by', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        # batch_op.add_column(sa.Column('2nd_blocked_by', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        # batch_op.add_column(sa.Column('1st_blocked_by', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        # batch_op.add_column(sa.Column('third_blocked_for', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        # batch_op.add_column(sa.Column('third_blocked_till', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        pass

    with op.batch_alter_table('media_property_occupancy_report', schema=None) as batch_op:
        batch_op.drop_column('po_date')

    # ### end Alembic commands ###
